In [1]:
pwd

'C:\\Users\\emre-'

In [2]:
cd Data_1

C:\Users\emre-\Data_1

In [3]:
cd clarusway-data-science-5-20-master

C:\Users\emre-\Data_1\clarusway-data-science-5-20-master

In [4]:
cd 1-projects/

C:\Users\emre-\Data_1\clarusway-data-science-5-20-master\1-projects

In [5]:
cd 01-EU_DS_DAPy_M1-(TrafficPoliceStops)

C:\Users\emre-\Data_1\clarusway-data-science-5-20-master\1-projects\01-EU_DS_DAPy_M1-(TrafficPoliceStops)

In [6]:
import numpy as np
import pandas as pd

In [7]:
ri = pd.read_csv("ri.csv",low_memory=False, index_col = "DatetimeIndex")

In [8]:
ri

,id,stop_date,stop_time,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
DatetimeIndex,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55,RI-2005-00001,2005-01-02,01:55,Zone K1,NaN,NaN,600,M,1985.0,20.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30,RI-2005-00002,2005-01-02,20:30,Zone X4,NaN,NaN,500,M,1987.0,18.0,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55,RI-2005-00004,2005-01-04,12:55,Zone X4,NaN,NaN,500,M,1986.0,19.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-06 01:30,RI-2005-00005,2005-01-06,01:30,Zone X4,NaN,NaN,500,M,1978.0,27.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-12 08:05,RI-2005-00006,2005-01-12,08:05,Zone X1,NaN,NaN,000,M,1973.0,32.0,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-31 22:46,RI-2015-47061,2015-12-31,22:46,Zone X1,NaN,NaN,000,M,1959.0,56.0,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X1,False
2015-12-31 22:47,RI-2015-47062,2015-12-31,22:47,Zone X4,NaN,NaN,500,M,1988.0,27.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2015-12-31 23:08,RI-2015-47063,2015-12-31,23:08,Zone X3,NaN,NaN,200,M,1980.0,35.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X3,False
2015-12-31 23:44,RI-2015-47064,2015-12-31,23:44,Zone K2,NaN,NaN,900,M,1984.0,31.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2,False
2015-12-31 23:48,RI-2015-47065,2015-12-31,23:48,Zone K3,NaN,NaN,300,M,1988.0,27.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False

In [9]:
ri.head(5)

,id,stop_date,stop_time,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
DatetimeIndex,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55,RI-2005-00001,2005-01-02,01:55,Zone K1,NaN,NaN,600,M,1985.0,20.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30,RI-2005-00002,2005-01-02,20:30,Zone X4,NaN,NaN,500,M,1987.0,18.0,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55,RI-2005-00004,2005-01-04,12:55,Zone X4,NaN,NaN,500,M,1986.0,19.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-06 01:30,RI-2005-00005,2005-01-06,01:30,Zone X4,NaN,NaN,500,M,1978.0,27.0,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-12 08:05,RI-2005-00006,2005-01-12,08:05,Zone X1,NaN,NaN,000,M,1973.0,32.0,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,False

In [10]:
ri.isnull()

,id,stop_date,stop_time,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
DatetimeIndex,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2005-01-02 20:30,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2005-01-04 12:55,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2005-01-06 01:30,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2005-01-12 08:05,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-31 22:46,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2015-12-31 22:47,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2015-12-31 23:08,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2015-12-31 23:44,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2015-12-31 23:48,False,False,False,False,True,True,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False

In [11]:
ri.isnull().sum()

id                            0
stop_date                     0
stop_time                     0
location_raw                  0
county_fips              480584
fine_grained_location    480584
police_department             0
driver_gender                 0
driver_age_raw                1
driver_age                 1638
driver_race_raw               0
driver_race                   0
violation_raw                 0
violation                     0
search_conducted              0
search_type_raw          462822
search_type              462822
contraband_found              0
stop_outcome                  0
is_arrested                   0
stop_duration                 0
out_of_state                808
drugs_related_stop            0
district                      0
frisk                         0
dtype: int64

In [12]:
ri.shape

(480584, 25)

In [13]:
ri.drop(["county_name"], axis = 1, inplace= True)

KeyError: "['county_name'] not found in axis"

In [ ]:
ri.shape

In [ ]:
ri.drop(["state"], axis = 1, inplace= True)

In [ ]:
ri.shape

In [ ]:
ri.count(axis = "columns")

In [ ]:
ri.dropna(axis=0,subset =["driver_gender"],inplace = True)

In [ ]:
ri.shape

In [ ]:
ri.is_arrested

In [ ]:
ri["is_arrested"] = ri["is_arrested"].astype('bool')

In [ ]:
ri["is_arrested"].dtype

In [ ]:
ri.stop_date

In [ ]:
ri.stop_time

In [ ]:
ri['stop_datetime'] =  ri["stop_date"] +" "+  ri["stop_time"]

In [ ]:
ri.set_index("stop_datetime", inplace=True)

In [ ]:
ri.to_csv("ri_index_stop.csv")

In [ ]:
ri.index.name = 'DatetimeIndex'

In [ ]:
ri.head()

In [ ]:
ri.to_csv("ri.csv")

In [ ]:
ri

In [ ]:
ri["violation"].unique()

In [ ]:
ri["violation"].value_counts(normalize=True) * 100

In [ ]:
female = ri[ri["driver_gender"] == "F"]

In [ ]:
male = ri[ri["driver_gender"] == "M"]

In [ ]:
ri["violation"].value_counts(normalize=True) * 100

In [ ]:
female["violation"].value_counts(normalize =True)*100

In [ ]:
male["violation"].value_counts(normalize =True)*100

In [ ]:
female_and_speeding = female[female["violation"]=="Speeding"]

In [ ]:
female_and_speeding["stop_outcome"].value_counts(normalize =True)*100

In [ ]:
male_and_speeding = male[male["violation"]=="Speeding"]

In [ ]:
male_and_speeding["stop_outcome"].value_counts(normalize =True)*100

In [ ]:
ri["search_conducted"] = ri["search_conducted"].astype('bool')

In [ ]:
ri["search_conducted"].value_counts(normalize =True)

In [ ]:
ri["search_conducted"].mean()

In [ ]:
female["search_conducted"].mean()

In [ ]:
male["search_conducted"].mean()

In [ ]:
ri.groupby("driver_gender")["search_conducted"].mean()

In [ ]:
ri.groupby(["driver_gender", "violation"])[["search_conducted"]].mean()

In [ ]:
ri.groupby(["violation", "driver_gender"])[["search_conducted"]].mean()

In [ ]:
ri["search_type"].value_counts()["Protective Frisk"]

In [ ]:
ri["frisk"] = (ri["search_type"]=="Protective Frisk")

In [ ]:
ri["frisk"].dtype

In [ ]:
ri["frisk"].sum()

In [ ]:
searched= ri[ri["search_conducted"]== True]

In [ ]:
searched

In [ ]:
ri.groupby(["driver_gender"])["frisk"].mean()

In [ ]:
searched["frisk"].mean()

In [ ]:
ri.to_csv("ri.csv")

In [ ]:
ri.head()